/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface VirtualBitcoinInterface extends ethers.utils.Interface {
  functions: {
    "COIN()": FunctionFragment;
    "DECIMALS()": FunctionFragment;
    "MAX_COIN()": FunctionFragment;
    "NAME()": FunctionFragment;
    "PIZZA_POWER_PRICE()": FunctionFragment;
    "PRECISION()": FunctionFragment;
    "SUBSIDY_HALVING_INTERVAL()": FunctionFragment;
    "SYMBOL()": FunctionFragment;
    "accSubsidy()": FunctionFragment;
    "accSubsidyBlock()": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "buyPizza(uint256)": FunctionFragment;
    "changePizza(uint256,uint256)": FunctionFragment;
    "decimals()": FunctionFragment;
    "genesisEthBlock()": FunctionFragment;
    "mine(uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "pizzaCount()": FunctionFragment;
    "pizzaPrice(uint256)": FunctionFragment;
    "pizzas(uint256)": FunctionFragment;
    "powerOf(uint256)": FunctionFragment;
    "sellPizza(uint256)": FunctionFragment;
    "subsidyAt(uint256)": FunctionFragment;
    "subsidyOf(uint256)": FunctionFragment;
    "symbol()": FunctionFragment;
    "testMint()": FunctionFragment;
    "totalPower()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "COIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "DECIMALS", values?: undefined): string;
  encodeFunctionData(functionFragment: "MAX_COIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "NAME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PIZZA_POWER_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUBSIDY_HALVING_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "SYMBOL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accSubsidy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accSubsidyBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "buyPizza",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changePizza",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "genesisEthBlock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mine", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pizzaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pizzaPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pizzas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "powerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellPizza",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subsidyAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subsidyOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "testMint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "COIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DECIMALS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_COIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "NAME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PIZZA_POWER_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUBSIDY_HALVING_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SYMBOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "accSubsidy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accSubsidyBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyPizza", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changePizza",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genesisEthBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pizzaCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pizzaPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pizzas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "powerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellPizza", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subsidyAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subsidyOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalPower", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "BuyPizza(address,uint256,uint256)": EventFragment;
    "ChangePizza(address,uint256,uint256)": EventFragment;
    "Mine(address,uint256,uint256)": EventFragment;
    "SellPizza(address,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuyPizza"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangePizza"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Mine"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SellPizza"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class VirtualBitcoin extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: VirtualBitcoinInterface;

  functions: {
    COIN(overrides?: CallOverrides): Promise<[BigNumber]>;

    "COIN()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    DECIMALS(overrides?: CallOverrides): Promise<[number]>;

    "DECIMALS()"(overrides?: CallOverrides): Promise<[number]>;

    MAX_COIN(overrides?: CallOverrides): Promise<[BigNumber]>;

    "MAX_COIN()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    NAME(overrides?: CallOverrides): Promise<[string]>;

    "NAME()"(overrides?: CallOverrides): Promise<[string]>;

    PIZZA_POWER_PRICE(overrides?: CallOverrides): Promise<[BigNumber]>;

    "PIZZA_POWER_PRICE()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    "PRECISION()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    SUBSIDY_HALVING_INTERVAL(overrides?: CallOverrides): Promise<[number]>;

    "SUBSIDY_HALVING_INTERVAL()"(overrides?: CallOverrides): Promise<[number]>;

    SYMBOL(overrides?: CallOverrides): Promise<[string]>;

    "SYMBOL()"(overrides?: CallOverrides): Promise<[string]>;

    accSubsidy(overrides?: CallOverrides): Promise<[BigNumber]>;

    "accSubsidy()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    accSubsidyBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "accSubsidyBlock()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    allowance(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { remaining: BigNumber }>;

    "allowance(address,address)"(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { remaining: BigNumber }>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    buyPizza(
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyPizza(uint256)"(
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changePizza(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changePizza(uint256,uint256)"(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    "decimals()"(overrides?: CallOverrides): Promise<[number]>;

    genesisEthBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "genesisEthBlock()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    mine(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mine(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    "name()"(overrides?: CallOverrides): Promise<[string]>;

    pizzaCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "pizzaCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    pizzaPrice(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "pizzaPrice(uint256)"(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pizzas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        power: BigNumber;
        accSubsidy: BigNumber;
      }
    >;

    "pizzas(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        power: BigNumber;
        accSubsidy: BigNumber;
      }
    >;

    powerOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "powerOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sellPizza(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellPizza(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    subsidyAt(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    "subsidyAt(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    subsidyOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "subsidyOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    "symbol()"(overrides?: CallOverrides): Promise<[string]>;

    testMint(overrides?: Overrides): Promise<ContractTransaction>;

    "testMint()"(overrides?: Overrides): Promise<ContractTransaction>;

    totalPower(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalPower()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  COIN(overrides?: CallOverrides): Promise<BigNumber>;

  "COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

  DECIMALS(overrides?: CallOverrides): Promise<number>;

  "DECIMALS()"(overrides?: CallOverrides): Promise<number>;

  MAX_COIN(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX_COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

  NAME(overrides?: CallOverrides): Promise<string>;

  "NAME()"(overrides?: CallOverrides): Promise<string>;

  PIZZA_POWER_PRICE(overrides?: CallOverrides): Promise<BigNumber>;

  "PIZZA_POWER_PRICE()"(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  "PRECISION()"(overrides?: CallOverrides): Promise<BigNumber>;

  SUBSIDY_HALVING_INTERVAL(overrides?: CallOverrides): Promise<number>;

  "SUBSIDY_HALVING_INTERVAL()"(overrides?: CallOverrides): Promise<number>;

  SYMBOL(overrides?: CallOverrides): Promise<string>;

  "SYMBOL()"(overrides?: CallOverrides): Promise<string>;

  accSubsidy(overrides?: CallOverrides): Promise<BigNumber>;

  "accSubsidy()"(overrides?: CallOverrides): Promise<BigNumber>;

  accSubsidyBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "accSubsidyBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  allowance(
    user: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    user: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buyPizza(
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyPizza(uint256)"(
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changePizza(
    pizzaId: BigNumberish,
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changePizza(uint256,uint256)"(
    pizzaId: BigNumberish,
    power: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  genesisEthBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "genesisEthBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  mine(
    pizzaId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mine(uint256)"(
    pizzaId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  pizzaCount(overrides?: CallOverrides): Promise<BigNumber>;

  "pizzaCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  pizzaPrice(
    power: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "pizzaPrice(uint256)"(
    power: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  pizzas(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      owner: string;
      power: BigNumber;
      accSubsidy: BigNumber;
    }
  >;

  "pizzas(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      owner: string;
      power: BigNumber;
      accSubsidy: BigNumber;
    }
  >;

  powerOf(pizzaId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "powerOf(uint256)"(
    pizzaId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sellPizza(
    pizzaId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellPizza(uint256)"(
    pizzaId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  subsidyAt(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "subsidyAt(uint256)"(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  subsidyOf(
    pizzaId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "subsidyOf(uint256)"(
    pizzaId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  testMint(overrides?: Overrides): Promise<ContractTransaction>;

  "testMint()"(overrides?: Overrides): Promise<ContractTransaction>;

  totalPower(overrides?: CallOverrides): Promise<BigNumber>;

  "totalPower()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    COIN(overrides?: CallOverrides): Promise<BigNumber>;

    "COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    DECIMALS(overrides?: CallOverrides): Promise<number>;

    "DECIMALS()"(overrides?: CallOverrides): Promise<number>;

    MAX_COIN(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    NAME(overrides?: CallOverrides): Promise<string>;

    "NAME()"(overrides?: CallOverrides): Promise<string>;

    PIZZA_POWER_PRICE(overrides?: CallOverrides): Promise<BigNumber>;

    "PIZZA_POWER_PRICE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    "PRECISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    SUBSIDY_HALVING_INTERVAL(overrides?: CallOverrides): Promise<number>;

    "SUBSIDY_HALVING_INTERVAL()"(overrides?: CallOverrides): Promise<number>;

    SYMBOL(overrides?: CallOverrides): Promise<string>;

    "SYMBOL()"(overrides?: CallOverrides): Promise<string>;

    accSubsidy(overrides?: CallOverrides): Promise<BigNumber>;

    "accSubsidy()"(overrides?: CallOverrides): Promise<BigNumber>;

    accSubsidyBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "accSubsidyBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyPizza(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyPizza(uint256)"(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changePizza(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "changePizza(uint256,uint256)"(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    genesisEthBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "genesisEthBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    mine(pizzaId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "mine(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    pizzaCount(overrides?: CallOverrides): Promise<BigNumber>;

    "pizzaCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    pizzaPrice(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pizzaPrice(uint256)"(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pizzas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        power: BigNumber;
        accSubsidy: BigNumber;
      }
    >;

    "pizzas(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        owner: string;
        power: BigNumber;
        accSubsidy: BigNumber;
      }
    >;

    powerOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "powerOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellPizza(pizzaId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "sellPizza(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    subsidyAt(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "subsidyAt(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    subsidyOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "subsidyOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    testMint(overrides?: CallOverrides): Promise<void>;

    "testMint()"(overrides?: CallOverrides): Promise<void>;

    totalPower(overrides?: CallOverrides): Promise<BigNumber>;

    "totalPower()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      amount: null
    ): EventFilter;

    BuyPizza(
      owner: string | null,
      pizzaId: BigNumberish | null,
      power: null
    ): EventFilter;

    ChangePizza(
      owner: string | null,
      pizzaId: BigNumberish | null,
      power: null
    ): EventFilter;

    Mine(
      owner: string | null,
      pizzaId: BigNumberish | null,
      subsidy: null
    ): EventFilter;

    SellPizza(owner: string | null, pizzaId: BigNumberish | null): EventFilter;

    Transfer(from: string | null, to: string | null, amount: null): EventFilter;
  };

  estimateGas: {
    COIN(overrides?: CallOverrides): Promise<BigNumber>;

    "COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_COIN(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX_COIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    NAME(overrides?: CallOverrides): Promise<BigNumber>;

    "NAME()"(overrides?: CallOverrides): Promise<BigNumber>;

    PIZZA_POWER_PRICE(overrides?: CallOverrides): Promise<BigNumber>;

    "PIZZA_POWER_PRICE()"(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    "PRECISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    SUBSIDY_HALVING_INTERVAL(overrides?: CallOverrides): Promise<BigNumber>;

    "SUBSIDY_HALVING_INTERVAL()"(overrides?: CallOverrides): Promise<BigNumber>;

    SYMBOL(overrides?: CallOverrides): Promise<BigNumber>;

    "SYMBOL()"(overrides?: CallOverrides): Promise<BigNumber>;

    accSubsidy(overrides?: CallOverrides): Promise<BigNumber>;

    "accSubsidy()"(overrides?: CallOverrides): Promise<BigNumber>;

    accSubsidyBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "accSubsidyBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    allowance(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyPizza(power: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "buyPizza(uint256)"(
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    changePizza(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changePizza(uint256,uint256)"(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    genesisEthBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "genesisEthBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    mine(pizzaId: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "mine(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    pizzaCount(overrides?: CallOverrides): Promise<BigNumber>;

    "pizzaCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    pizzaPrice(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pizzaPrice(uint256)"(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pizzas(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "pizzas(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    powerOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "powerOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellPizza(pizzaId: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "sellPizza(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    subsidyAt(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "subsidyAt(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    subsidyOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "subsidyOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    testMint(overrides?: Overrides): Promise<BigNumber>;

    "testMint()"(overrides?: Overrides): Promise<BigNumber>;

    totalPower(overrides?: CallOverrides): Promise<BigNumber>;

    "totalPower()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    COIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "COIN()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DECIMALS()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_COIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MAX_COIN()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "NAME()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PIZZA_POWER_PRICE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PIZZA_POWER_PRICE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PRECISION()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUBSIDY_HALVING_INTERVAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "SUBSIDY_HALVING_INTERVAL()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SYMBOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "SYMBOL()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accSubsidy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "accSubsidy()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accSubsidyBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "accSubsidyBlock()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allowance(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address)"(
      user: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyPizza(
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyPizza(uint256)"(
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changePizza(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changePizza(uint256,uint256)"(
      pizzaId: BigNumberish,
      power: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    genesisEthBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "genesisEthBlock()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mine(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mine(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pizzaCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "pizzaCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pizzaPrice(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pizzaPrice(uint256)"(
      power: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pizzas(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pizzas(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    powerOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "powerOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellPizza(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellPizza(uint256)"(
      pizzaId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    subsidyAt(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "subsidyAt(uint256)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    subsidyOf(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "subsidyOf(uint256)"(
      pizzaId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testMint(overrides?: Overrides): Promise<PopulatedTransaction>;

    "testMint()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    totalPower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalPower()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
